version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin your-aws-account-id.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t pet-tracker-fe .
      - docker tag pet-tracker-fe:latest your-aws-account-id.dkr.ecr.eu-central-1.amazonaws.com/pet-tracker-fe:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push your-aws-account-id.dkr.ecr.eu-central-1.amazonaws.com/pet-tracker-fe:latest
artifacts:
  files: '**/*'
