version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2022-07-07/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/
      - kubectl version --client
      -
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 084828567158.dkr.ecr.eu-central-1.amazonaws.com
      - IMAGE_URI=084828567158.dkr.ecr.eu-central-1.amazonaws.com/pet-tracker-fe:latest
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t pet-tracker-fe .
      - docker tag pet-tracker-fe:latest 084828567158.dkr.ecr.eu-central-1.amazonaws.com/pet-tracker-fe:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
        - docker push $IMAGE_URI
        - echo Updating kubeconfig for EKS...
        - aws eks update-kubeconfig --name frontend-micro-frontend-cluster --region eu-central-1
        - echo Deploying to EKS...
        - sed -i "s|IMAGE_URI|$IMAGE_URI|g" k8s/deployment.yaml
        - kubectl apply -f k8s/deployment.yaml
        - kubectl apply -f k8s/service.yaml
artifacts:
  files: '**/*'
