apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: IMAGE_URI
          ports:
            - containerPort: 80
